swagger: '2.0'
info:
  version: 0.1.0
  title: Withings-API
host:  wbsapi.withings.net

schemes: 
  - "https"
produces:
 - application/json

x-rate-limit: 10

paths:
  /v2/measure?action=getactivity:
    get:
      description: |
        Retrieves a summary of daily activity information for a user for a given date or range of dates. The summary includes information about the step count, active calories burned, seconds of soft, moderate, and vigorous activity.
      operationId: getActivity
      parameters:
        - name: userid
          in: query
          description: identifies the individual for which to retrieve data
          required: true
          type: number
        - name: date
          in: query
          description: a single date for which to retrieve data (format YYYY-MM-DD); takes precedence over other date parameters 
          required: false
          type: string
        - name: startdateymd
          in: query
          description: a start date for a time frame of data to retrieve (format YYYY-MM-DD); requires enddateymd parameter
          required: false
          type: string
          x-coupled-with: [enddateymd]
        - name: enddateymd
          in: query
          description: an end date for a time frame of data to retrieve (format YYYY-MM-DD); requires enddateymd parameter
          required: false
          type: string
          x-coupled-with: [startdateymd]
      responses: 
        200:
            description: activity list response
            schema: 
              $ref: '#/definitions/ActivityResponse' 

  /v2/measure?action=getmeas:
    get:
      description: |
        Retrieves a summary of daily activity information for a user for a given date or range of dates. The summary includes information about the step count, active calories burned, seconds of soft, moderate, and vigorous activity.
      operationId: getActivity
      parameters:
        - name: userid
          in: query
          description: identifies the individual for which to retrieve data
          required: true
          type: number
        - name: date
          in: query
          description: a single date for which to retrieve data (format YYYY-MM-DD); takes precedence over other date parameters 
          required: false
          type: string
        - name: startdateymd
          in: query
          description: a start date for a time frame of data to retrieve (format YYYY-MM-DD); requires enddateymd parameter
          required: false
          type: string
          x-coupled-with: [enddateymd]
        - name: enddateymd
          in: query
          description: an end date for a time frame of data to retrieve (format YYYY-MM-DD); requires enddateymd parameter
          required: false
          type: string
          x-coupled-with: [startdateymd]
      responses: 
        200:
            description: activity list response
            schema: 
              $ref: '#/definitions/ActivityResponse' 



definitions:
  ActivityResponse:
    description: the schema of daily activity responses
    allOf:
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64